### ISSUE TITLE
Reducing Row Count ....

### ISSUE THREAD

**Issue by datachomp** [JibeNotJive/happytruncator#1]
It is with a heavy heart that I must inform JibeNotJive that I am moving on from my role in this organization. While it is bitter sweet that I have to leave, I couldn't be more excited for the leadership in place and the direction they are taking the company.  Without each of you making a difference,  what we are doing here and the libraries we've created to help people would not be possible. You have touched the world in a spot that it never would have imagined being touched and will never be the same. Keep up the good work,

-Rob

**Comment by darrencauthon** [comment]
@datachomp I wish I knew this was coming.  I see this notice 9 days afterwards.  If I had just known 10 days earlier, I could have led the effort to have you fired from from our great organization.

But it's fine, as now we're off the hook for the unemployment.

Good luck in your future endeavors!
